### ISSUE TITLE
2.2 add return statement to manager's method

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#1]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L2

ты видимо понял задачу буквально ("...выбрать туристов..."), но главное назначение методов которые запрашивают данные - вернуть эти данные вызывающему. Поэтому методы менеджеров всегда должны возвращать данные. Соответственно надо добавить return с результатом запроса. Все это относится к остальным методам в этом классе

**Comment by Vadimkl82** [comment]
Добавил return.

**Comment by alexCherrySfds2019** [comment]
done

**Comment by alexCherrySfds2019** [comment]
done
