### ISSUE TITLE
2.2 move SOQLs to manager

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#10]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristService.cls#L4

**Comment by Vadimkl82** [comment]
исправил. добавил в класс TouristManager метод getByEmailLastName.

**Comment by alexCherrySfds2019** [comment]
done

**Comment by alexCherrySfds2019** [comment]
done
