### ISSUE TITLE
2.2 incoming list is overwrited

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#11]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristService.cls#L3

у тебя входящие в метод туристы полностью игнорируются, т.е. никак не участвуют в логике

**Comment by Vadimkl82** [comment]
исправил.

**Comment by alexCherrySfds2019** [comment]
done

**Comment by alexCherrySfds2019** [comment]
done
