### ISSUE TITLE
2.2 move to FlightManager

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#13]
https://github.com/Vadimkl82/sf-senla-courses/blob/abfc1ab021c3278e8d43eae7d5e54cf56ce78b36/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L51

**Comment by Vadimkl82** [comment]
Создал новый класс FlightManager.cls и добавил в него два метода: public static List<Flight__c> getByStartDate и public static  List<Flight__c> getByNoTrip
