### ISSUE TITLE
2.2 change the method's signature

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#2]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L2

изменить тип возвращаемого значения в сигнатуре метода, можно также поменять название с choose... на get...  - это более понятно и стандартный подход. это относится и к остальным методам

**Comment by Vadimkl82** [comment]
Изменил типы возвращаемых значений в методах и их названия.

**Comment by alexCherrySfds2019** [comment]
done

**Comment by alexCherrySfds2019** [comment]
done
