### ISSUE TITLE
2.2 add input validation

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#3]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L2

можно добавить валидацию импута (вдруг придет пустая строчка - зачем делать лишний запрос, это ударит по лимитам). это относится и к остальным методам

**Comment by Vadimkl82** [comment]
Добавил валидацию к методам.

**Comment by alexCherrySfds2019** [comment]
в методе
https://github.com/Vadimkl82/sf-senla-courses/blob/abfc1ab021c3278e8d43eae7d5e54cf56ce78b36/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L15

здесь

https://github.com/Vadimkl82/sf-senla-courses/blob/abfc1ab021c3278e8d43eae7d5e54cf56ce78b36/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L16

также добавь проверку на пустоту листа ages.isEmpty()
также null принято писать с маленькой буквы (вместо Null)

**Comment by Vadimkl82** [comment]
исправил
