### ISSUE TITLE
2.2 change method's name

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#4]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L2

поскольку много похожих методов, отказаться от цифр на конце метода и заменить их на название параметра поиска . например: chooseTourists1 -> getTouristsByFirstName. это же относится ко всем остальным методам.

даже лучше переименовать  -> getByFirstName, т.к. весь менеджер работает с туристами.

**Comment by Vadimkl82** [comment]
Изменил названия методов с учетом параметров поиска.

**Comment by alexCherrySfds2019** [comment]
done
