### ISSUE TITLE
2.2 for each field in SOQL - new line

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#5]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L4

вместо SELECT Name, Age__c

лучше 
SELECT Name, 
Age__c

если будет SELECT Name, Age__c, (SELECT Trip__r.Name, Trip__r.Start_Date__c FROM flying__r)

можно 
SELECT Name, 
Age__c, 
(SELECT Trip__r.Name, Trip__r.Start_Date__c FROM flying__r)

или если внутренни запрос слишком длинный (не влезает в экран) его также можно разбить
SELECT Name, 
Age__c, 
(SELECT Trip__r.Name, 
Trip__r.Start_Date__c 
FROM flying__r)

**Comment by Vadimkl82** [comment]
Произвел форматирование SOQL запросов.

**Comment by alexCherrySfds2019** [comment]
done
