### ISSUE TITLE
2.2 change parameters

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#7]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristManager.cls#L11

по задаче: выбрать туристов (имя, возраст) с возрастом 20, 22, 24 года. твой же метод может вернуть только туристаов одного возраста. Надо переделать чтобы можно было передать массив возрастов

**Comment by Vadimkl82** [comment]
Добавил массив в параметр метода.

**Comment by alexCherrySfds2019** [comment]
done
