### ISSUE TITLE
2.2 list to improve

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#8]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/NumberUtility.cls#L1

замечания ко всем методам:

1) должны что-то возвращать
2) обычно методы которые возвращают начинаются с get, но для 1 и 3 тоже подойдет. Palindrom - это плохо т.к. а) не глагол 2) начинается с большой буквы. методы которые возвращают булены лучше называть с is... has...
3) параметры методов должны начинаться с маленькой буквы
4) убери лишние пробелы; List < Integer > ->  List<Integer>

**Comment by Vadimkl82** [comment]
устранил все замечания

**Comment by alexCherrySfds2019** [comment]
done
