### ISSUE TITLE
2.2 improve the logic

### ISSUE THREAD

**Issue by alexCherrySfds2019** [Vadimkl82/sf-senla-courses#9]
https://github.com/Vadimkl82/sf-senla-courses/blob/7fed79494f25e738ad6cae60c3be8c5f42d8a3ca/%D0%94%D0%97%20lecture_2.2/TouristService.cls#L1

а можешь вкратце пояснить какая логика у метода? т.е. какие общие шаги и что они делают?

**Comment by Vadimkl82** [comment]
логика была следующая:
делаю запрос и получаю список туристов с фамилиями и email;
затем проводим перебор существующих туристов в первом цикле;
во втором цикле хотел сравнить нового туриста со списком всех существующих туристов и если совпадают записи полей фамилия и email - пометить как дубликат.

переделал файл на основе разбора ДЗ.

**Comment by alexCherrySfds2019** [comment]
смотри, что не так:
1) тебе незачем прям все туристы в базе, тебе для сравнения нужны только те, у кого такие же значения двух полей как у новых туристов
2) соответственно надо 
2.1) переделать getByEmailLastName в менеджере (добавить параметры) и переименовать его (можно на getTourists)
2.2)  перед вызовом getTourists добавить в markDuplicates собирание значений двух полей с новыых туристов
